const BASE_API_URL = "http://localhost:3000/api/"; // Remplacez par l'adresse de votre API

enum pathAPI {
  USER_LIST = BASE_API_URL + "users/usersList",
  REGISTER = BASE_API_URL + "users/register",
  LOGIN = BASE_API_URL + "users/login",
  PROFILE = BASE_API_URL + "users/profile",
  ACTIVATE = BASE_API_URL + "users/activate",
  DEACTIVATE = BASE_API_URL + "users/deactivate",
  UPDATE_PASSWORD = BASE_API_URL + "users/updatePassword",
  UPDATE_USER = BASE_API_URL + "users/updateUser",
  FORCE_PASSWORD_UPDATE = BASE_API_URL + "users/forcePasswordUpdate",
  SCREEN_MODE_UPDATE = BASE_API_URL + "users/updateScreenMode",
  GET_ALL_CLIENTS = BASE_API_URL + "clients/getAll",
  ADD_CLIENT = BASE_API_URL + "clients/addClient",
  EDIT_CLIENT_FIELD = BASE_API_URL + "clients/editClientById",
  GET_ALL_ORDERS = BASE_API_URL + "orders/getAll",
  GET_ORDER_BY_ID = BASE_API_URL + "orders/getOrderById/",
  EDIT_ORDER_FIELD = BASE_API_URL + "orders/editOrderById",
  GET_PRODUCTS_BY_ORDER = BASE_API_URL + "products/getProductByOrder/",
  GET_ARTICLES = BASE_API_URL + "articles/getAll",
  ADD_ARTICLE = BASE_API_URL + "articles/addArticle",
  GET_MAX_QUOYE_NUMBER = BASE_API_URL + "orders/getMaxQuoteNumber",
  GET_CLIENT_CONTACTS = BASE_API_URL + "contacts/getContactByIdClient/",
  ADD_ORDER = BASE_API_URL + "orders/add",
  ADD_CONTACT = BASE_API_URL + "contacts/add",
  VALIDATE_ORDER = BASE_API_URL + "orders/validateOrder",
  GET_TAGS = BASE_API_URL + "tags/getAllTags",
}
export default pathAPI;
